### ISSUE TITLE
How to debug the output of webdev --release ?

### ISSUE THREAD

**Issue by my2iu** [dart-lang/webdev#1002]
I was making a small webxr vr prototype in Windows: https://github.com/my2iu/tojam2020

When I build it with `webdev build --no-release` it runs fine, but when I build it with `webdev build --release` the generated js throws all sorts of type errors when it runs, but it's impossible to figure out what's going wrong because everything is minified. Is there some sort of intermediate optimization/debugging options I can enable with webdev to figure out what's going on?

Also, is there a way to generate a build with only the essential files? I noticed that if I took the `--no-release` build and removed all the dart files, the total size was smaller than the `--release` build. So a lot of the files in the `--release` build must be extra, but I don't know what they are.

**Comment by jakemac53** [comment]
> Is there some sort of intermediate optimization/debugging options I can enable with webdev to figure out what's going on?

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-debug-my-release-mode-web-app-dart2js

> So a lot of the files in the `--release` build must be extra, but I don't know what they are.

This is most likely because you have more than one application that is being compiled? In dev mode the apps are split up into several pieces, which are shared across other apps. In release mode each app is totally independent and produced a single file for the whole app (unless you use deferred loading).

For instance if you have a lot of tests then this would be expected behavior. You could do a build of just your `web` directory in order to not compile the tests.
