### ISSUE TITLE
I used flutter for my ecom app and I keep getting this error: NoSuchMethodError. The getter ‘id’ was called on null. Receiver: null Tried calling: id

### ISSUE THREAD

**Issue by justinekatebe69** [dart-lang/webdev#1056]
I used flutter for my ecom app and I keep getting this error: NoSuchMethodError. The getter ‘id’ was called on null. Receiver: null Tried calling: id

How do i get it to go away?

**Comment by natebosch** [comment]
There is not enough information here for us to know what the problem is, and github issues are not the best venue to get support with your code. Stack Overflow might be a better place to try.

You don't indicate here if this error is surfacing in your code (in which case the solution is to find where you are calling `something.id` and handle the case where that `something` is nul), or if the error is surfacing in some tool code. A stack trace should make that more clear. If the error is surfacing in a tool and you believe it stems from this repository, you can comment and we can investigate. If its surfacing in some other tool you likely need to file an issue on the flutter repo.
