### ISSUE TITLE
[dwds?] On hover / getObject fails

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#1138]
In VSCode, when launching and stopped at a Flutter web app, I see:

![Screen Shot 2020-10-08 at 2 32 08 PM](https://user-images.githubusercontent.com/2119553/95521326-223ec380-097e-11eb-9b03-470c251e1b80.png)

Hovering on primitives and lists seems to be fine, but I get `<error>: <getObject: NoSuchMethod: ...>` consistently on regular objects.

Flutter version is:
```
Flutter 1.23.0-8.0.pre.243 • channel master • https://github.com/flutter/flutter.git
Framework • revision cb0bdb4994 (9 minutes ago) • 2020-10-08 14:12:03 -0700
Engine • revision 2eac514f26
Tools • Dart 2.11.0 (build 2.11.0-186.0.dev)
```

I've seen this on master as well.  Not sure if this is DWDS.  Eval seems to still work fine, but I cannot drill into the object.

@grouma

**Comment by grouma** [comment]
I think this is caused by https://github.com/Dart-Code/Dart-Code/issues/2855

@DanTup can you confirm?

**Comment by vsmenon** [comment]
FWIW, I'm on this version of the plugin: https://dartcode.org/releases/v3-15/

**Comment by vsmenon** [comment]
Ahh, yes, I'm hitting what appears to be https://github.com/flutter/flutter/issues/67506 - looks like a fix is on route.  Thanks!

**Comment by DanTup** [comment]
Yep, I think this is the issue linked above. I've handled this in Dart-Code, though I think it may still be a bug in dwds that should be fixed (`offset` should be ignored for non-collection objects, rather than crashing - which is what the VM appears to do, since this didn't occur there).

There is a dev build of Dart-Code at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.16.0-dev.3 that includes the if you'd really like a fix before the next release.
