### ISSUE TITLE
webdev appears to ignore additional sources in target

### ISSUE THREAD

**Issue by simolus3** [dart-lang/webdev#1200]
Small repro: https://github.com/simolus3/webdev-repo, compare running `build_runner build` vs `webdev build` in there (run `build_runner clean` inbetween!)

I have a project with the following structure:

```
my_app
  lib/
    builders.dart
  source/
    index.foo
  build.yaml
  pubspec.yaml
```

I have a regular builder copying `index.foo` to `index.bar`, that builder will also invoke a post-process builder copying `index.bar` to `web/index.html`. Both builders are only writing to the build cache and they're both enabled. My default target includes `source/**`.
When I run `build_runner build`, I see the generated `index.html` in `.dart_tool/build/generated/$packageName/web`. So when I run `webdev serve`, I expect to see that generated asset too. However, `webdev` doesn't invoke either builder at all.

**Comment by natebosch** [comment]
One difference is that `build_runner build` still runs in dev mode while `webdev build` has an implicit `--release` argument. `webdev serve` should build in dev mode. This was to keep backward compatibility with `pub build` which was release mode and `pub serve` which was dev mode. I don't see any reason to think that might be a factor here though.

I can't think of any reason the post process builders wouldn't work. @jakemac53 is the most familiar at this point I think with build filtering that might be impacting this.

**Comment by jakemac53** [comment]
I noticed that even `pub run build_runner serve` exhibits this behavior 😕

**Comment by jakemac53** [comment]
Ah, it has something to do with the `buildDirs` - `pub run build_runner build web` also does it.

**Comment by jakemac53** [comment]
Ok, this is actually working as intended. Post process builders can not cause new files to be built, that were not built as a part of the normal build.

Webdev, by default only builds the `web` directory, and the `source/index.bar` file is not an input to any normal action that outputs a file under `web`, so it is _not built_. Thus, it is not available to the post process builder as an input, because it wasn't built, and the builder doesn't run.

You can work around this by explicitly building the `source` directory as well - `webdev serve web:8080 source:8081`.

What it sounds like really is this is yet another use case for https://github.com/dart-lang/build/issues/1689.

**Comment by simolus3** [comment]
That makes sense. Thanks for looking into it and for sharing the workaround!
