### ISSUE TITLE
Support a --no-sound-null-safety flag 

### ISSUE THREAD

**Issue by Blimster** [dart-lang/webdev#1217]
If I use a non null-safe package as a dependency in a null-safe package, I get an Error like this:
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:logging

For solutions, see https://dart.dev/go/unsound-null-safety
```

But there is no solution provided on the linked page.

The funny thing is, that my package depends on a non-null safe version of logging, because I also have a dev dependency to build_runner because it is required for webdev. But build_runner only works with non null-safe versions of logging at the moment.

**Comment by grouma** [comment]
@jakemac53 do you know what's going on here? Webdev should just work assuming `package:build_runner` supports null safety.

**Comment by jakemac53** [comment]
For the `dart`, `flutter`, and most other tools this is handled with the `--no-sound-null-safety` flag.

For build_runner its more complicated, because it has no idea what null safety is. The builders do, and do support configuration though.

For instance on the web, the build_web_compilers builder is what should be configured. You can do this in a `build.yaml` file like this:

```yaml
targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        options:
          sound_null_safety: false
```

This can also be done with command line configuration `--define=build_web_compilers:entrypoint=sound_null_safety=false`. The `webdev` tool could support a `--no-sound-null-safety` argument and convert it to that argument for build daemon, which might make the most sense?

**Comment by grouma** [comment]
Repurposing this issue for support of the flag. This likely isn't a large priority given the supported workaround.

**Comment by Blimster** [comment]
The suggested solution is perfect for me.

Even there is a workaround, I think that the priority should be higher, because null safety is the actual big thing and I guess the community needs some time to migrate all the packages and we have to live with unsound null safety a while (especially on the web).

**Comment by jakemac53** [comment]
One thing to note is that this flag is only needed in the case of an out of order migration. This means that you have migrated before your dependencies, which is allowed but not advised, generally.

One reason this is discouraged is that any time you run `pub upgrade`  you could be broken if one of your dependencies migrates and does not release that as a breaking change.

I do think it would be worth supporting the flag in any case though - as this is a supported option generally and for good reason.

I don't think that the `build_runner` tool itself should do this though - it would mean baking in a lot of knowledge about things that it really shouldn't know about. We would probably end up wanting to add a notion of null safety to the entire build system as a general concept but I don't think that is a good approach - the build system doesn't even understand the web, vm, flutter, or even dart compilation as concepts directly.
I am not so sure if `build_runner`
