### ISSUE TITLE
On variable drill down, inherited fields are not visible

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#1263]
In the variables window here, `this` is of type [`PageController`](https://github.com/flutter/flutter/blob/3fd3447f9676b71d91ee81e32f335c702cef8e7c/packages/flutter/lib/src/widgets/page_view.dart#L112).  When I expand, I see fields defined directly in that class.  I don't see fields inherited from the superclass, [`ScrollController`](https://github.com/flutter/flutter/blob/c51fba97364209f1991fa41a74ecd67c41caf381/packages/flutter/lib/src/widgets/scroll_controller.dart#L44) (e.g., `_initialScrollOffset` or `keepScrollOffset`): 

![Screen Shot 2021-03-06 at 1 13 13 PM](https://user-images.githubusercontent.com/2119553/110249263-39341280-7f2a-11eb-9063-c051cd87604d.png)

This is with:
```
> flutter --version
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (3 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

FYI - @annagrin @grouma - not sure how pervasive this is, but I think fairly high priority if so.

**Comment by vsmenon** [comment]
![Screen Shot 2021-03-07 at 9 59 00 AM](https://user-images.githubusercontent.com/2119553/110249613-c9bf2280-7f2b-11eb-92ef-3cc25c54abee.png)

This is one level up in the stack.  In this case, `this` is a subclass of `State`, and I similarly cannot see fields from `State`:

https://github.com/flutter/flutter/blob/e5322acc77f116803c93cfe1d538ae3c16a19423/packages/flutter/lib/src/widgets/framework.dart#L884

**Comment by annagrin** [comment]
I don't see the same outcome - I wonder if this is could be related to  https://github.com/dart-lang/sdk/issues/45266. 
I am currently working on the fix.

**Comment by annagrin** [comment]
I created a smaller repro - apparently evaluation works fine, but local variables returned from dwds do not contain inherited fields - note that watch window and expression evaluation box evaluate `b.t` but it does not appear in local variables view.

We currently use ddc runtime function `sdk_utils.getFields` to get the fields of the object (`this` in code below), and it does not seem to list all the inherited properties.

Suggestion:
- Add getting all fields functionality to the ddc runtime
- Add a more concise way for a debugger to ask for fields an object
- If possible, it should use dart evaluation instead of js evaluation
   Can we create dart ddc runtime library that the debugger can use?

https://github.com/dart-lang/webdev/blob/51ad9e76a8283499059a7357f7ada8a48aacd87d/dwds/lib/src/debugging/instance.dart#L276

![image](https://user-images.githubusercontent.com/12737689/111715606-709b9c80-8811-11eb-8330-624c9039d137.png)

**Comment by annagrin** [comment]
This thread is now split into the following two issues, closing as duplicate:
- https://github.com/dart-lang/sdk/issues/45266
- https://github.com/dart-lang/sdk/issues/45387
