### ISSUE TITLE
Remove backwards compatibility for postEvent() and registerExtension()

### ISSUE THREAD

**Issue by nshahan** [dart-lang/webdev#1342]
Tracking issue so we know when it is safe to cleanup the backwards compatibility code I'm landing in the Dart SDK that still writes events to the `console.debug` log when calling `postEvent()` and registerExtension().

**Comment by nshahan** [comment]
@grouma Can you help identify when it is safe to remove the backwards compatibility? In other words, when do we know dwds will not be interacting with an old SDK doesn't use the function hooks introduced in babe0982da2d3b41b6a7fa30d9862a238f7a8459?

**Comment by grouma** [comment]
This is not a concern for internal users. For Flutter users we pin the version of DWDS so that too shouldn't be a concern. For webdev the SDK is based off the min SDK defined in the pubspec: https://github.com/dart-lang/webdev/blob/6306a2a489dde3f3103a26e247fda38c79c95466/webdev/pubspec.yaml#L12

We could model this as a breaking change in DWDS and simply remove the logic to ensure that old version of webdev are not impacted.
