### ISSUE TITLE
[webdev] Add a flag to launch chrome signed into the default profile and enable extensions

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1490]
Currently webdev launches chrome using temp profile, so the users cannot use their extensions while debugging. Can we allow launching a window that is signed in as the user's default profile?

Notes:

There seems to be a bug/feature in chrome that only uses the existing session with `--user-data-dir`.  The existing session cannot open a debug port that dwds needs. 

Workaround: copy the default profile to a temp directory, and pass it to chrome. That seems to work, but takes time to copy the profile.

**Comment by alanknight-wk** [comment]
Nice! It would help with the launch time if webdev could re-use the previous temporary profile, rather than launching a new one each time. You'd need to be able to force a new profile in order to get updates from the previous one. Or even if if started from a completely empty profile, users could install their extensions once and keep using it.

I'm also not sure how that works with authorization schemes. In the past I've run things in a persistent temporary profile but I wasn't able to have it authorized properly to the company web app, and the thing I wanted to debug needed to do that. But that may just be because I didn't understand how to do that properly.

**Comment by annagrin** [comment]
Hi Alan! Nice to hear from you! 

As for not reusing the new directory - we only do that on windows due to some flakiness that reusing the directory on windows results in. Would you be able to open a new issue for that? You can also try modifying webdev code here to try things out on your machine (commenting out the `!Platform.isWindows` condition): https://github.com/dart-lang/webdev/blob/465596197afa5949ce2a233083f0d887856ced94/webdev/lib/src/serve/chrome.dart#L45

For the issue at hand, I can add a flag for passing a user directory so you can pass the original chrome user directory, but for now only for non-windows platforms - we would need to solve the flakiness issue first.
