### ISSUE TITLE
Make it easier to debug a Flutter Web app with the Dart Debug Extension

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1508]
- Start a Flutter web app (I'm using https://github.com/flutter/gallery) with `flutter run -d chrome` from the command line
- Copy-and-paste the URL from the guest Chrome profile into a Chrome profile with the Dart Debug Extension installed
- Click the Dart Debug Extension. It should say you first need authenticate. Click OK [image 1]
- The URL that opens (for me it is http://127.0.0.1:55813/$dwdsExtensionAuthentication) cannot connect [image 2]

image 1:
![Screen Shot 2022-02-16 at 12 09 01 PM](https://user-images.githubusercontent.com/21270878/154348028-7285ccf5-4991-4438-ac16-dded792a2c2a.png)

image 2:
![Screen Shot 2022-02-16 at 12 09 23 PM](https://user-images.githubusercontent.com/21270878/154347688-fc129ce4-c4b7-4b34-9f3a-4707c0bdc816.png)

**Comment by elliette** [comment]
@grouma  @DanTup  I think you two have context on this workflow. Was this ever supported? Thanks!

**Comment by elliette** [comment]
From offline chat with @grouma:

- In this case, we would 1) not expect authentication to be required and 2) for the authentication URL extension to work

* DWDS simply hosts a URL and if you try to hit it, it will redirect you to sign in. Once you sign in you get a simple response.
* It seems like DWDS is no longer hosting that URL, or the URL that you are directed to is not the one that it's hosting

**Comment by DanTup** [comment]
I've never used the Dart Debug extension with the Chrome device, only with the web-server device (which would just give you the URL and not spawn Chrome). Is it supported to use the debug extension if Flutter is connected via the Chrome debug port?

(it's been a while since I've done much with this, so I don't know if my knowledge is very up-to-date :) )

**Comment by elliette** [comment]
Thanks for the responses! 

Re: "Is it supported to use the debug extension if Flutter is connected via the Chrome debug port?" - I'm not sure, will need to investigate. In this case, the profile didn't have the Chrome debug port (since I had copy-pasted it over to my profile)

**Comment by DanTup** [comment]
> In this case, the profile didn't have the Chrome debug port

Oh, I thought `flutter run -d chrome` always launched Chrome using the debug port. Is that not the case? (My latest understanding was that the `chrome` device ran using the debug port and the `web-server` device used the debug extension.. but now I'm not so sure!)

**Comment by elliette** [comment]
Hmm looking into this a bit more. 

@DanTup - do you mind sharing how you use the Dart Debug Extension with `web-server` device? It seems like debugging isn't enabled by default (when I run `flutter run -d web-server`, my Flutter app doesn't contained the injected client needed for debugging). 

Regarding the flow  `flutter run -d chrome` flow described above, I don't think it's officially supported. However  I'm surprised it was even partially working a few weeks ago. It is completely unsupported now, and looking at the code it makes sense why:

* When the Dart Debug Extension icon is clicked, DWDS only launches Dart DevTools if `serveDevTools` is true: [code link](https://github.com/dart-lang/webdev/blob/3f729f70dd05cd1a4c70814be44f35171398008c/dwds/lib/src/handlers/dev_handler.dart#L557). 
This is determined by whether or not a `devtoolsLauncher` has been provided as a parameter to `DWDS.start`: [code link](https://github.com/dart-lang/webdev/blob/3f729f70dd05cd1a4c70814be44f35171398008c/dwds/lib/dwds.dart#L158)
* In Flutter, we alias `DWDS.start` as [`devtoolsLauncher`](https://github.com/flutter/flutter/blob/1dd24b8af858e1c875da39649061cb5022811430/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L192), and when we invoke the `devtoolsLauncher` **alias**, we don’t provide a  `devtoolsLauncher` **parameter** (the naming of multiple `devtoolsLaunchers` could definitely be improved!): [code link](https://github.com/flutter/flutter/blob/1dd24b8af858e1c875da39649061cb5022811430/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L277-L298). Therefore `serveDevTools` is `false`. 

None of this has changed in over a year, which is why it is puzzling this changed for me in the past 3 weeks.

**Comment by DanTup** [comment]
> do you mind sharing how you use the Dart Debug Extension with web-server device? It seems like debugging isn't enabled by default (when I run flutter run -d web-server, my Flutter app doesn't contain the injected client needed for debugging).

There's not really anything special to supporting web-server in VS Code. For the most simple case (where you press `F5` in VS Code with the `web-server` device selected):

- We run `flutter run --machine --start-paused -d web-server` (plus some additional flags like `--web-server-debug-backend-protocol` that probably aren't important here)
- We wait for an event like `[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:53108","launched":false}}]` which tells use the URL of the web app for us to spawn in the browser
- We ensure the message "Waiting for connection from Dart debug extension at http://localhost:53108" is visible to the user (I think we detect this and show some additional text, like "Please click the Dart Debug extension button in the spawned browser window")
- The user clicks the button in the extension, and everything gets connected up and `flutter run` just continues as if it was a non-web app

I tried "Run without Debugging" but as far as I can tell, we actually follow the same path right now (we still run with `--start-paused`) and everything works the same.


> Regarding the flutter run -d chrome flow described above, I don't think it's officially supported. However I'm surprised it was even partially working a few weeks ago.

I've never tried to use the extension with anything other than the web-server device, so I don't have any useful knowledge here, although:

> In Flutter, we alias DWDS.start as [devtoolsLauncher](https://github.com/flutter/flutter/blob/1dd24b8af858e1c875da39649061cb5022811430/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L192), and when we invoke the devtoolsLauncher alias, we don’t provide a devtoolsLauncher parameter (the naming of multiple devtoolsLaunchers could definitely be improved!): [code link](https://github.com/flutter/flutter/blob/1dd24b8af858e1c875da39649061cb5022811430/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L277-L298). Therefore serveDevTools is false.

I'm assuming the first two mentions or `devtoolsLauncher` here should say `dwdsLauncher`... `devtoolsLauncher` seems to be an argument _to_ `dwdsLauncher`, and the issue is that when `dwdsLauncher` is invoked, it's never provided a `devtoolsLauncher`. This seems odd, although I'm not sure why launching DevTools matters here - the extension should work via DWDS and doesn't rely on DevTools at all?

Btw, I'm not sure if I entirely understand the goal. Is it to make the Chroe device _work_ with the debug extension? And if so, in what ways would it differ to the existing web-server device (if any?)?

**Comment by elliette** [comment]
Closing this out, pretty sure this is WAI. The `chrome` device does not support using the Dart Debug Extension.
