### ISSUE TITLE
Support running frontend server tests with sound null safety.

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1591]
DWDS test infrastructure does not support executing tests with null safety mode using frontend server, since the null-safe `dart_sdk.js` file is non included in the dart sdk:

```
➜  dwds git:(master) ✗ ls ${HOME}/dart-sdk/lib/dev_compiler/kernel/amd
dart_sdk.js     dart_sdk.js.map require.js
```

Options for solutions:
- include the `dart_sdk_sound.js` in the dart SDK
- not rely on dart SDK JavaScript and source maps being included in the SDK and instead should investigate if we can produce them from the kernel file during the build (`ddc_platform.dill` and `ddc_platform_sound.dill`)

```
➜  dwds git:(annagrin/fix-locations-breakpoints) ✗ ls ${HOME}/dart-sdk/lib/_internal
allowed_experiments.json             ddc_platform_sound.dill              strong.sum
dart2js_platform.dill                ddc_sdk.dill                         vm
dart2js_platform_unsound.dill        fix_data.yaml                        vm_platform_strong.dill
dart2js_server_platform.dill         js_dev_runtime                       vm_platform_strong_product.dill
dart2js_server_platform_unsound.dill js_runtime                           wasm
ddc_outline_sound.dill               libraries.dart
ddc_platform.dill                    sdk_library_metadata
```

**Comment by nshahan** [comment]
When we released null safety my plan was to stop including the compiled sdk.js files entirely since they were bloating the size of the packaged download. We were already including a version of the SDK for each module system and then we would be doubling the number to support sound and weak null safety. I ended up leaving the weak versions in the SDK for backwards compatibility. 

In build_runner builds the sdk.js file is compiled from the .dill files packaged with the SDK. I believe it actually ignores the prebuilt weak version and just build their own as needed.

Does this test infrastructure rely on build_runner at all? If so is it possible to request the sdk.js files from the build outputs in the `.dart_tool` directory?

**Comment by annagrin** [comment]
This tests is not using build runner to build, it is mimicking flutter tools (and uses frontend server). Will need to investigate how to build dill files and js files for the tests. Note: flutter tools uses prebuilt files for this purpose currently.

**Comment by nshahan** [comment]
Good to know, and it sounds like we would like to update flutter tools to build versions as needed as well.

We could look at build_runner to see what commands they are running to build the sdk.js file and bake them into the test setup.
