### ISSUE TITLE
Dart Debug Extension no longer works

### ISSUE THREAD

**Issue by ecarlson94** [dart-lang/webdev#2025]
As of today, every time I attempt to run the dart debugger, I get a notification "Cannot authenticate user". This happens on both Edge and Chrome. I can't develop anymore without this extension. I didn't realize how dependent on it I was. :{

I hope it helps to know that I am using the web-server device.

Edit: tone

**Comment by rello86** [comment]
same issue

**Comment by mrpurpleknight** [comment]
Same for me

**Comment by beasteh** [comment]
+1 same issue...

**Comment by natesitton80** [comment]
+1 having this issue as well

**Comment by rello86** [comment]
i think the problem is somehow related to the following :

JsObject get _windowContext => JsObject.fromBrowserObject(window);
dwds/web)/client.dart line 318

**Comment by elliette** [comment]
Sorry for the inconvenience!

I just rolled back to the previous extension version (the one that was working). It's been submitted to the the Chrome WebStore, and should hopefully be published in a few hours or (usually at most) a day. **You can determine that you have the new version by visiting chrome://extensions and checking for Dart Debug Extension version 1.32 (not version 1.31, this is the version that is not working.)** 

In order to fix the underlying issue, do you mind providing repro steps for how you are running your app and connecting with the Dart Debug Extension?

Thank you!

**Comment by elliette** [comment]
Version `1.32` is now available in the Chrome WebStore, so you can uninstall the current extension and re-install it here:

https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm
