### ISSUE TITLE
Only host one directory (web) by default

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#226]
Scenario: package w/ web + test directories
Run `webdev serve`

Expect: only `web` is hosted
Actual: both web and test

If the user wants more, they can always specify the ones they want, right?

CC @grouma @jakemac53

**Comment by jakemac53** [comment]
I personally would prefer it to be more explicit like it is today

**Comment by kevmoo** [comment]
Explain?

**Comment by natebosch** [comment]
Defaults come from here: https://github.com/dart-lang/build/blob/58b15553381c2e807e3dcc798f9a363dff8dad2f/build_runner/lib/src/entrypoint/options.dart#L33

If you added `example/` or `benchmark/` directories to your package those would get served too.

I'm open to changing the defaults in `build_runner`, or we could make `webdev` add an explicit argument when no rest args were otherwise included and change the default only here.

I don't see a significant reason for `build_runner` to have a more broad default than `webdev`, but changing it only here could maybe limit the impact of a breaking version rev?

**Comment by kevmoo** [comment]
> but changing it only here could maybe limit the impact of a breaking version rev?

My thoughts.

At a minimum, I'd argue we should only open one when 'launch with chrome' is set

**Comment by grouma** [comment]
Correction. Defaults were copied from there but actually reside here: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/command/serve_command.dart#L16

I did this for consistency but to be honest would prefer if just `web` was the default. We can do this as a part of `2.0.0` and won't be a breaking change obviously to `build_runner`.

**Comment by kevmoo** [comment]
SGTM!
