### ISSUE TITLE
getObject: (-32603) Unexpected DWDS error for getObject: Unsupported operation: Only libraries, instances, classes, and scripts are supported for getObject

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/webdev#2446]
I am unable to view a getter in Dart's dev tools with the following app on web only. I am unsure if this is supposed to work, but I don't see why it shouldn't.

<img width="1127" alt="Screenshot 2024-06-11 at 5 40 38 PM" src="https://github.com/dart-lang/webdev/assets/20613561/6512efd8-250b-4484-82bb-65040b65da30">

Steps to repro:
1. create a flutter app with the code below
2. run app on web
3. set break point on the print statement
4. view the local vars in dev tools

```dart
import 'package:flutter/material.dart';

class CustomHttpRequest {
  const CustomHttpRequest(this.bytes);
  final List<int> bytes;
  Stream<List<int>> get body => Stream.value(bytes);
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Column(
            children: [
              FilledButton(
                onPressed: () {
                  const r = CustomHttpRequest([1, 2, 3]);
                  print('r body: ${r.body}');
                },
                child: const Text('request'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by CoderDake** [comment]
Error thrown here: https://github.com/dart-lang/webdev/blob/9ada46fc00f4052a02b1816c534f2df67d2efc1b/dwds/lib/src/debugging/inspector.dart#L416-L417

We'll have to take a closer look into how we might be able to grab that information and pass it along.

**Comment by Lorenzobettega** [comment]
I encountered the same issue in my code when I attempted to cast() an Object List. 
The debugger showed a generic error in the devTools for web.
my flutter doctor: [√] Chrome - develop for the web
I'm thinking that this is related to the old issue: #2297
![image](https://github.com/dart-lang/webdev/assets/84482292/01dc83cd-2e57-48d5-8e3c-cb47da5fc55a)

**Comment by bkonyi** [comment]
@elliette seems to think this is an issue that has come up before. She'll share the context if she can find it, but otherwise we'll have to dig in to this to figure out what's going on.

**Comment by elliette** [comment]
This is the issue I was thinking of: 
* https://github.com/dart-lang/webdev/issues/2309
* (related) https://github.com/dart-lang/webdev/issues/2336

This seems like a separate issue though

**Comment by derekxu16** [comment]
Thank you for the reproduction instructions, @Jordan-Nelson. The problem here is that the ability to request an instance of a `_ControllerStream` is currently broken. Here's how I created a minimal reproduction of this problem as a DWDS test case:

1. I added `final stream = Stream.value(1);` after this line: https://github.com/dart-lang/webdev/blob/645a068e707a85ff00e23d17a1d458689069735b/fixtures/_testSound/example/scopes/main.dart#L22
2. After [this line](https://github.com/dart-lang/webdev/blob/645a068e707a85ff00e23d17a1d458689069735b/dwds/test/instances/common/instance_common.dart#L380), I added the following test case

        test('for a stream', () async {
          final remote = await inspector.jsEvaluate(
            libraryVariableExpression('stream', compilationMode),
          );
          final instance = await inspector.instanceFor(remote);
          expect(instance!.kind, InstanceKind.kPlainInstance);
          final classRef = instance.classRef!;
          expect(classRef.name, '_ControllerStream<int>');
          expect(inspector.isDisplayableObject(instance), isTrue);
        });

`test/instances/instance_test.dart` fails when run after making the changes above. Here's an excerpt from the logs:

```
[FINE] ClassMetadata: Could not create class metadata for {type: object, className: _ControllerStream.new, description: _ControllerStream.new, objectId: -56064532640991652.1.2}:
Unexpected error from chrome devtools:
text: Uncaught
exception:
  preview: null
  description: Error
    at Object.throw_ [as throw] (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:9456:11)
    at [_subscribe] (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:39649:21)
    at [_createSubscription] (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:36508:46)
    at _ControllerStream.new.listen (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:36474:53)
    at get length (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:23587:14)
    at Object._get (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:9356:18)
    at Object.getObjectMetadata (http://localhost:41141/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:9190:23)
    at _ControllerStream.new.<anonymous> (<anonymous>:4:23)
  type: object
  value: null
attempted JS eval: `        function(arg) {
          const sdk = require('dart_sdk');
          const dart  = sdk.dart;
          return dart.getObjectMetadata(arg);
        }
      `
```

It looks some DDC changes will be needed to fix this. @Markzipan and @nshahan, can you take a look at this when you get the chance?

**Comment by nshahan** [comment]
@natebiggs 
I don't think this is directly related to your async rewrites change but maybe your experience could help identify where this is failing and why?

**Comment by biggs0125** [comment]
I tried to repro this locally using the instructions @derekxu16 listed above but I was unable to. What version of Dart are you using when seeing this failure?

**Comment by biggs0125** [comment]
Chatted with @derekxu16 offline and we realized this failure is only reproducible if you also add the following to the test group 'instanceRef' in `instance_common.dart`:
```
test('for a stream', () async {
  final remoteObject = await inspector.jsEvaluate(
    libraryVariableExpression('stream', compilationMode),
  );
  final ref = await inspector.instanceRefFor(remoteObject);
  expect(ref!.kind, InstanceKind.kPlainInstance);
  final classRef = ref.classRef!;
  expect(classRef.name, '_ControllerStream<int>');
  expect(
    classRef.id,
    'classes|dart:async|_ControllerStream<int>',
  );
  expect(inspector.isDisplayableObject(ref), isTrue);
});
```

**Comment by biggs0125** [comment]
Okay I was able to figure out that the issue here is with this [invocation of the `length` getter](https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/debugger.dart#L290) on the `_ControllerStream` object.

`_ControllerStream` only allows [one subscription at a time](https://github.com/dart-lang/sdk/blob/main/sdk/lib/async/stream_controller.dart#L686) and each call to `length` [subscribes to the stream](https://github.com/dart-lang/sdk/blob/main/sdk/lib/async/stream.dart#L1296).

The issue here is that we are calling the `length` getter on every object being debugged. As outlined by the vm service we should only be invoking a `length` getter for [specific types](https://github.com/dart-lang/sdk/blob/main/pkg/vm_service/lib/src/vm_service.dart#L4621). I'm opening a CL in DDC to fix this.

**Comment by biggs0125** [comment]
Landing this fix: https://dart-review.googlesource.com/c/sdk/+/380220

This fix should get included in the next Dart release. Until then users will get errors if the same Stream object is queried multiple times.
