### ISSUE TITLE
Make VS Code and Webdev agree on package: URIs

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#350]
Capturing from the meeting, but not sure of where the issues are. @jakemac53 do you have more details?

**Comment by jakemac53** [comment]
@jacob314 would know more here, its pretty specific to the widget inspector I believe.

**Comment by jacob314** [comment]
Currently when the kernel transformer is run for regular flutter, all URIs show up as 
`package:`
uris
currently when the kernel transformer is run for flutter_web that is not the case and uris are of the form
`dart-packages-or-something:packages/`
It would be nice if all the uris exposed to the kernel transformer for flutter_web match those from flutter.
I know there is the issue of the `/web/` directory but it would be nice if we could find a solution for it that still lets us use `package:` urls ideally everywhere. That would simplify things for IDEs both for widget creation and any other cases where the file locations from kernel are leaking into the debugging output.

**Comment by jakemac53** [comment]
Note that `package:` uris can only point at the `lib` directory of a package. They are only intended for pointing to shared code. Uris like `package:../web` should be disallowed by all tools if they aren't already. Beyond just being gross uris like that are unsafe, allowing you to reach arbitrary paths on the users machine.

We do not have a standard way of referencing files outside of the `lib` directory other than relative or absolute uris, and `kernel` will convert relative uris to absolute uris.

Absolute uris are not an option for build systems that want to produce hermetic output, because they would contain paths that are specific to a given machine.

Therefore, in `package:build` (and internally in bazel) we use a custom scheme to signify absolute paths that are actually relative to the root of the package. That scheme is configurable to whatever we want, but we currently use `org-dartlang-app:`. Note that this scheme is only used for files outside of the `lib` directory.

I am curious what uris flutter uses for apps in the `example` or `test` dirs? My assumption would be absolute paths which aren't an option for us.

**Comment by DanTup** [comment]
Thanks for all the info, I understand this much better now :-)

As an editor though, it kinda sucks to be dealing with non-fs paths, because we have to start coding in logic that understands these schemes (and usually they are not well specified, nor guaranteed to not be broken). We've had many bugs using package: URIs in VS Code's debugger and recently moved *everything* back to FS paths. We still have outstanding issues with adding breakpoints inside SDK source because it also has its own similar scheme that VS Code can't easily relate back to files on disk, so using Go-to-Definition to get to an SDK file and stepping into it with the debugger, the files are considered separate as far as VS Code is concerned and we can't reconcile them.

Is there any way we can put this logic into the inspector service code? For example, Flutter launched the project and knows where the root is, why does it need an editor to tell if again what the project root is (setPubRootDirectories)? If it's to support other packages (eg. you have a `path` dependency), could we make it do the translation (IIRC inspector runs in the VM and has real access to the package mapping). And then could it translate back to FS paths when it raises inspect events?

**Comment by jakemac53** [comment]
Within the vm service protocol itself, we actually do not report uris with these weird schemes. Today the uris are a bit broken actually due to a ddc issue (see https://github.com/dart-lang/sdk/issues/36736), but in general they will report either `package:` paths or relative paths. Those paths may actually be relative to the directory being served (so for instance `web/main.dart` might show up as `main.dart`). That is so it lines up with how they show up in chrome devtools, but its negotiable what path we actually report there.

The main problem I believe is in the kernel transformer for the widget inspector. That runs at build time, and injects some uris into the compiled kernel files. We could provide it enough information such that it could strip out the custom schemes or something? We do have access to the custom scheme at the point we create the kernel transformer. cc @jacob314 wdyt?

This would still cause a problem if vscode tried to set the absolute uri for the package as the root though, we would only want to strip out the custom scheme and convert that to a relative path.

**Comment by DanTup** [comment]
> This would still cause a problem if vscode tried to set the absolute uri for the package as the root though

But does whatever receives `setPubRootDirectories` have the knowledge to convert from `file://` URIs to whatever is required? (I don't know how this works internally, so I'm not sure if it's feasible).

Leaking the knowledge of how these URIs are made into to the editors will make it much more difficult to change. I was very much looking forward to removing the package-parsing code from VS Code (it's not documented and we've had bugs in it, for ex. the SDK's is hand-rolled). Now the debugger doesn't need it I think it's only used for tooltips (and with LSP that'll move to the server too).

Ofc, we can do it if we need to. If we do, we should try to document it as explicitly as possible. Many of the VM issues took a while to resolve because it's often not clear if something is a bug because the spec is vague (for ex. it has "URIs" all around the place with nothing to indicate which types are supported, preferred or will be returned!).

**Comment by jakemac53** [comment]
> But does whatever receives `setPubRootDirectories` have the knowledge to convert from `file://` URIs to whatever is required? (I don't know how this works internally, so I'm not sure if it's feasible).

That would be a question for @jacob314 

> Leaking the knowledge of how these URIs are made into to the editors will make it much more difficult to change. I was very much looking forward to removing the package-parsing code from VS Code (it's not documented and we've had bugs in it, for ex. the SDK's is hand-rolled). Now the debugger doesn't need it I think it's only used for tooltips (and with LSP that'll move to the server too).

I definitely agree that vscode shouldn't know about our custom uris, at least not unless we actually created a general standard for them.

**Comment by DanTup** [comment]
FWIW, my comments were aimed at standard Flutter too, though I don't know if that ship has already sailed. When I last tested in master I was still (unexpectedly?) getting file URIs, so I haven't seen the package-URIs or made any changes in VS Code for them yet.

**Comment by jakemac53** [comment]
So do all uris come through as absolute `file:` uris from flutter?

**Comment by DanTup** [comment]
They did in my testing, though Jacob said they should be package URIs now (a recent change). I'm not sure why I'm not seeing this though (VS code will not handle anything other than file URIs right now).

**Comment by grouma** [comment]
Is this still an issue? Can this be closed?

cc @alan-knight @jakemac53

**Comment by jacob314** [comment]
We still need to fix this issue.

**Comment by jakemac53** [comment]
In fact we probably made this worse recently... we will give package: uris for sources under lib but outside of that we are giving the uris as they would be loaded in chrome. These are file uris that are relative to the directory being served, and it is going to be hard for vscode to make sense of them.

**Comment by jakemac53** [comment]
@DanTup it would be good to start pushing on this, we have some basic debugging stuff working now (stepping, pausing, resuming).

The current state is that we will provide `package:` uris for all files under the `lib` dir of a package, so hopefully that is relatively straightforward to deal with. 

For other files it looks like we currently provide an `org-dartlang-app://<path-relative-to-package-root>` uri but we should likely not be doing that. I think what we make those uris look like is somewhat up in the air, or maybe we could even make it configurable.

We could also have a mode where we convert everything to absolute uris, but those are really ugly in devtools. If vscode isn't surfacing them directly that might be more reasonable though for that case.

**Comment by DanTup** [comment]
Things that are in the same format as non-web (for ex. `package:` URIs) should already just work. For files outside lib, I think we currently expect file URIs (I think that's what non-web does?).

Tbh, my real preference would be for file URIs for everything. We've had many bugs with package URIs and still have unresolved issues with the SDK (for ex. https://github.com/flutter/flutter/issues/27189). I don't that's good for everyone else though :-)

> We could also have a mode where we convert everything to absolute uris, but those are really ugly in devtools

I think if things are ugly, they're better fixed in the clients display than the protocol being biased. The protocol should be boring and consistent.

I can easily enable the debugger (and setPubRoots thing) in VS Code so if you want a build, or want me to try running it against anything, let me know.

**Comment by jakemac53** [comment]
Talked with @grouma a bit more and we realized an option to configure the URIs is not viable because you might have multiple tools attached which want different styles of uris.

At this point I am leaning towards asking VsCode/Intellij/Devtools to understand the `org-dartlang-app` scheme as a path relative to the root of the package, and we keep things as they current stand on our end. For devtools I think all that really means is stripping out that uri from the sources view so it only shows the path (we don't want actual users to see this uri).

@jwren @DanTup @jacob314 how do you all feel about standardizing support around org-dartlang-app?

We could also change the name of that scheme to something different if desired.

**Comment by jakemac53** [comment]
cc @bkonyi 

If we do go with a custom scheme, it would be good if the VM was consistent.

**Comment by jakemac53** [comment]
> I think if things are ugly, they're better fixed in the clients display than the protocol being biased. The protocol should be boring and consistent.

One problem with this is there really isn't an efficient and robust way to go from an absolute file uri to a package: uri or package root relative path. You have to compare each absolute uri against all known package locations until you find one with a matching prefix. On the flipside though there is a trivial way to go from a package: uri to an absolute file uri, and its fast and robust.

**Comment by DanTup** [comment]
> At this point I am leaning towards asking VsCode/Intellij/Devtools to understand the org-dartlang-app scheme as a path relative to the root of the package,

This still feels a bit weird to me, though I think the important thing is that it's consistent and easy mappable.

> One problem with this is there really isn't an efficient and robust way to go from an absolute file uri to a package: uri or package root relative path. You have to compare each absolute uri against all known package locations until you find one with a matching prefix.

If I understand correctly, won't we have to do this anyway - (eg. to set breakpoints)?

**Comment by jakemac53** [comment]
> If I understand correctly, won't we have to do this anyway - (eg. to set breakpoints)?

Hmm, I suppose that is true from the vscode (and probably intellij) standpoint. From a devtools standpoint the reverse is true because they only deal in the file uris that we send them right now.

There is a difference though in that if devtools wanted to surface `package:` uris in the sources list, they would have to do this for every source which becomes O(#sources * #packages), while vscode/intellij would only have to do the mapping one file at a time when you set breakpoints (just O(#packages)).

Or, devtools could just show absolute uris but that seems really sub par. Being able to search by package: uri is much nicer.

**Comment by DanTup** [comment]
> while vscode/intellij would only have to do the mapping one file at a time when you set breakpoints (just O(#packages)).

We do this at the start of the debug session, so if you set a lot of breakpoints in a lot of files it would be > O(#files-with-breakpoints * #packages), but fair point, it's less work here.

> Being able to search by package: uri is much nicer.

If it's specifically searching, you could translate the other way (convert the `package:foo/` search into the absolute path). I'm sure you care about the display too though. In VS Code we don't currently provide the Scripts list (though we probably should).

Is there any scope to provide both from the VM/proxy?

**Comment by jakemac53** [comment]
> Is there any scope to provide both from the VM/proxy?

Interesting thought... today we have `uri` on Script but we could add an additional field `packageUri` or something?

**Comment by DanTup** [comment]
Yeah, that way we could have consistent file:// URIs for *everything* for when that's most appropriate (eg. the user clicks on a stack frame in the call stack and we need to open a file in the editor) but also a nicer URI for displaying. The VM already supports either format for most things that are sent to it (eg. when setting a breakpoint with `addBreakpointWithScriptUri` it will take either `file://` or `package:`).

That said, there's still a little weirdness around display of non-lib files.. It's weird to have `package:foo/foo.dart` alongside a long fs path for something that's in the same package as far as the user is concerned. I wonder if showing them as like `package:foo/../bin/blah.dart` would be weird?

**Comment by jakemac53** [comment]
> I wonder if showing them as like `package:foo/../bin/blah.dart` would be weird?

Ya, we definitely don't want to do that imo.

My suggestion would be to show a relative path, which is relative to the package root (so like web/main.dart).

**Comment by jakemac53** [comment]
@bkonyi wdyt about adding an extra field to `Script` to represent the "human readable" uri, and then clarifying the existing docs for `uri` to be an absolute file or data uri?

**Comment by DanTup** [comment]
> My suggestion would be to show a relative path, which is relative to the package root (so like web/main.dart).

I was thinking about "other packages", though now I think about it, there shouldn't be any scripts from outside of lib folders except for the root package, right?

**Comment by jakemac53** [comment]
> I was thinking about "other packages", though now I think about it, there shouldn't be any scripts from outside of lib folders except for the root package, right?

Correct

**Comment by grouma** [comment]
Closing this. I think this is not an issue as debugging through VS code works.
