### ISSUE TITLE
Implement Flutter screenshot vm service method

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/webdev#447]
This is generally useful for debugging or filing issues. Could be implemented by delegating to `Page.captureScreenshot`.

**Comment by jakemac53** [comment]
@jonahwilliams just to confirm is this `ext.flutter.inspector.screenshot`? I can't find any docs or code for it so I don't know what the params or return values are supposed to be :).

**Comment by jonahwilliams** [comment]
It looks like I was mistaken and we don't actually use this for screenshots, instead each "device" type is responsible for implementing its own functionality - via adb commands for example.

In this case, instead of exposing it as a vmservice method it might be better to expose on a webdev client or handle somewhere, ultimately calling into the Page.captureScreenshot api and returning the decoded raw bytes

**Comment by jakemac53** [comment]
The advantage of leaving it as a part of the vm service is it would enable devtools or other tools that only talk to the app with that protocol to be able to use it :man_shrugging: . It is also trivial to implement that way. We would probably want to base64 encode the bytes or something since we have to return json but that should be fine I think.

Any concerns about that approach?

**Comment by jakemac53** [comment]
It sounds like we could name it whatever we want, since there is some code in the flutter tool that would be making a call to us. I would probably opt for `ext.webdev.screenshot` or something like that?

**Comment by jonahwilliams** [comment]
SGTM
