### ISSUE TITLE
[SEVERE] Error compiling dartdevc module

### ISSUE THREAD

**Issue by hpoit** [dart-lang/webdev#471]
https://gist.github.com/hpoit/8b610d10581c56ac2035e38062525201#file-gistfile1-txt-L34 
on macOS 10.13.6

**Comment by natebosch** [comment]
This looks like it's caused by the errors printed above  such as `Missing concrete implementation of OnActivate.onActivate`. If there are compilation errors in one module it can cascade into `AssetNotFoundException` in other modules.

Fix the errors in `hero_component.dart` and the build should succeed.

**Comment by hpoit** [comment]
My `hero_component.dart` is identical to https://github.com/angular-examples/toh-5/blob/master/lib/src/hero_component.dart
