### ISSUE TITLE
[SEVERE] Error compiling dartdevc module

### ISSUE THREAD

**Issue by hpoit** [dart-lang/webdev#473]
My hero_component.dart is identical to https://github.com/angular-examples/toh-5/blob/master/lib/src/hero_component.dart

Since you closed https://github.com/dart-lang/webdev/issues/471 without confirming the solution to the problem, I am re-opening it here.

**Comment by jakemac53** [comment]
This is a compile time error indicating a problem in user code.

It is entirely possible that is a problem with the TOH example itself, but it is very unlikely that it is a webdev or build package issue. We do not maintain those examples.

This could also be because TOH was written for a previous version of angular, or something else.

**Comment by hpoit** [comment]
Thanks for closing this issue on probability, instead of trying to help me solve it. 

If you find a place in https://github.com/angular-examples/toh-5 that says TOH that says it is Angular version-dependent, please show it to me.

**Comment by alorenzen** [comment]
The example explicitly depends on angular 5.0. That's a previous version of angular.

https://github.com/angular-examples/toh-5/blob/master/pubspec.yaml#L9

**Comment by hpoit** [comment]
Why would [`quickstart`](https://github.com/angular-examples/quickstart/blob/master/pubspec.yaml#L9) be on `angular: ^6.0.0-alpha` and the rest of TOH on `angular: ^5.0.0`? How does an AngularDart beginner follow up on the differences?

**Comment by hpoit** [comment]
What's the reasoning behind making `quickstart` run on an alpha release?
