### ISSUE TITLE
How to use different "build.yaml" files?

### ISSUE THREAD

**Issue by cedx** [dart-lang/webdev#55]
Support for `--config` flag is not planned: see #14 

But, from my point of view, it is required : my projects rely on the `sass_builder` package. This package has  an `outputStyle` option that let you choose between `expanded` and `compressed` output.

Using `pub run build_runner --config=<debug|release>`, I can have `expanded` output in `serve` mode, and   `compressed` output in `build` mode.

How can I reproduce this behavior using the `webdev` CLI?

**Comment by alorenzen** [comment]
Instead of `--config=<debug|release>`, you should just use the `--release` or `--no-release` flag. 

Then, you can specify different dev and release options for the `sass_builder` inside your package. See https://github.com/dart-lang/build/blob/be72ec4a35640a61f0ed61b0f038caadf46e47e5/build_config/README.md#configuring-builders-applied-to-your-package

Since we default to `--release` for `build` and `--no-release` for `serve`, you should get the behavior you want once you configure the `sass_builder` properly.

**Comment by cedx** [comment]
Wonderful ! Thanks @alorenzen for pointing this out.
