### ISSUE TITLE
"webdev build" ate my global CSS files

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/webdev#72]
I have a utility package of Angular components which I use in my apps (think Material components library).
This package comes with global css stylesheet which I used to include in index.html of an app in development like this:

` <link rel="stylesheet" href="packages/fnx_ui/css/fnx_ui.css">
`

It worked with "pub build" but doesn't work with "webdev build". It works with "webdev serve" though.

None of my css files from my package did make it to the final build. Other files from the package (fonts) are there, but not the css files.

**Comment by mehaase** [comment]
Hi @kevmoo I'm upgrading some things to Dart2/Angular5 this week and i just ran into the same thing. I have a global CSS file in one package that is supposed to be referenced from the `web/index.html` of another. In Dart1/Angular2 (yeah its been a while since I upgraded), I could load the global CSS file from another package like this:

```html
    <link rel='stylesheet' type='text/css'
          href='packages/ng_modular_admin/src/css/modular-admin.css'>
```

But now this file is not produced in the build directory. I noticed that `.font` files and other arbitrary extensions like `.dat` are copied into the build directory, so I guess that there's some special handling of CSS files but I'm not sure what I should do to declare that I want this CSS file to appear in the build output.

**Comment by natebosch** [comment]
If you're using `angular` then it ships with a [cleanup builders](https://github.com/dart-lang/angular/blob/354d1883ff037a3844d44ac07a3b63871083a792/angular/lib/src/build.dart#L98-L105) which removes `.html` and `.css` files.

[By default](https://github.com/dart-lang/angular/blob/354d1883ff037a3844d44ac07a3b63871083a792/angular/build.yaml#L36-L42) this is only enabled in release builds which is why you don't see it with `webdev serve` - `webdev serve` defaults to dev build while `webdev build` defaults to release build.

This also only happens in `lib/` if you have a CSS file in `web/` it shouldn't be cleaned up by angular.

> Also, somewhat ironically .scss files are copied to the build directory even though they are not needed as build artifacts...

If you are using `sass_builder` I would expect [those to be cleaned up](https://github.com/dart-league/sass_builder/blob/ac821bca17c207c0333c032e563eae2bfd0b537f/build.yaml#L14-L20).

If you are compiling sass outside the build system instead and don't have `sass_builder` in your deps then there isn't anything that would clean it up.

> Is there a way to configure which files get copied?

Not directly. You can implement a new `PostProcessBuilder` following the examples in angular and `sass_builder` to clean up whatever file extensions you'd like.
