### ISSUE TITLE
dwds Dependency on "devtools" doesn't seem to bring in any deps

### ISSUE THREAD

**Issue by iskakaushik** [dart-lang/webdev#720]
That package doesn't have a lib directory and seems to delegate heavily to devtools_server. It would make sense to remove this dependency.

cc: @rmacnak-google , @jason-simmons

**Comment by jakemac53** [comment]
This package is really weird - last I checked it works by publishing explicitly a `build` directory and the `devtools_server` package serves from that. 

You could make a good argument that `devtools_server` should encapsulate the `devtools` dep, but we would probably still need a `devtools` dep here in order to pin to a version that we know works with `dwds`.

**Comment by jakemac53** [comment]
cc @jacob314

**Comment by iskakaushik** [comment]
This is interesting in conjunction with https://github.com/dart-archive/dart_enhancement_proposals/blob/master/Accepted/0005%20-%20Package%20Specification/DEP-pkgspec.md, when you have a project that depends on devtools, it would result in an invalid `.packages` file. Specifically an entry for `devtools` that points to an invalid `lib` dir reference.

I discovered this issue downstream in Fuchsia where we try to take actions based on the presence of the value associated with a given pub package.

**Comment by jakemac53** [comment]
It is absolutely correct that reaching outside of the `lib` directory of dependencies is a hack - but this is not the only place it happens. It is defacto supported because pub does ship the entire package when you publish.

**Comment by jakemac53** [comment]
I am going to close this issue as we can't remove the dependency, but feel free to open a new one on `devtools`.
