### ISSUE TITLE
Slow loading chrome after refresh

### ISSUE THREAD

**Issue by moczix** [dart-lang/webdev#75]
I have issue here, i guess... created starter angular dart, then i compile it. everything is good for now. I go to chrome, to localhost:8080 it take 1second to boot up the starter app. I go to networks and see a lot of files, ddc.js which explain the 1sec time to boot up.
But after refresh page, its still 1 sec. The resources are not cached :( i tried on others browsers like firefox and opera.

With starter angular todo list, the boot up time is about 10seconds!

**Comment by kevmoo** [comment]
The first time you run `webdev serve` it can be slow – because all of the assets need to be generated.

After the first run, refreshing should be pretty quick – assuming you're only changing your app code.

Did you have `disable caching` checked in Chrome or something?

**Comment by 9thwall** [comment]
@kevmoo  When you say it can be slow, how slow is normal? I'm asking because it takes the basic angular-examples/quickstart 3 minutes on my machine to serve. Is this normal? 

`[INFO] Running build completed, took 3m 0s
[INFO] Caching finalized dependency graph completed, took 598ms
[INFO] Succeeded after 3m 1s with 2291 outputs (6425 actions)
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081`

**Comment by kevmoo** [comment]
For the first build, depending on your machine, that may be normal.

Try changing one file in the example app and see how long build takes – that should be super quick!

**Comment by 9thwall** [comment]
Ok great. thank you for the info.

**Comment by jakemac53** [comment]
closing as I don't think there is anything actionable left here
