### ISSUE TITLE
CORS issue when trying to use debug extension from VS Online

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#817]
I don't know if this is a webdev/dwds issue or because of VS Online's tunnelling/proxy, but when the debug extension tries to connect it gets blocked with this CORS error:

> Access to resource at 'https://0xxxxxxx3c-38491.app.online.visualstudio.com/$debug?sseClientId=db857xxxxxxxbd-0f52b02158e2' from origin 'chrome-extension://eljbmlghnomdjgdjmbdekegdkbabckhm' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is that fixable here by having the `$debug` endpoint include a header that allows the debug extension to access it?

(I'm not sure why I don't see this locally - maybe because it's not HTTPS, or because it's localhost?)

**Comment by grouma** [comment]
The SSE handler correctly sets the `Access-Control-Allow-Origin`.

See:
https://github.com/dart-lang/sse/blob/master/lib/server/sse_handler.dart#L20

And:
https://github.com/dart-lang/sse/blob/master/lib/server/sse_handler.dart#L144

I ran into a similar issue while working with proxy encoded URLs internally. It turned out the SSE handler wasn't actually handling the request, I suspect a similar issue. My guess is your request is getting router to something else.

**Comment by DanTup** [comment]
What is "origin" in that case? If it's the hostname of the web app, that's different to the hostname of the debug service for VS Online. For example:

web app: https://somelongguid-8080.app.online.visualstudio.com/
debug service: https://somelongguid-38491.app.online.visualstudio.com/$debug

This is because the internal port numbers are moved into the hostname and the port is always 443 (for HTTPS) in VS Online.

**Comment by grouma** [comment]
It's the hostname of the originator of the request.

**Comment by DanTup** [comment]
Ah got it, that's the Chrome-extension url when running locally (which would solve the issue if the header was present). Seems like this may be being lost by the VS Online tunnelling so I've raised https://github.com/microsoft/vscode/issues/84469. Thanks!
