### ISSUE TITLE
Unpin vm_service

### ISSUE THREAD

**Issue by dnfield** [dart-lang/webdev#896]
Futter would like to use vm_service - we have to manually pin ourselves to the same version as dwds at this point, because we also use dwds, and this will make it harder for us to upgrade either package moving forward.

**Comment by grouma** [comment]
This is infeasible by design. We pin the version of the package because we provide a specific implementation of the VM service:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/services/chrome_proxy_service.dart#L39

Non-breaking changes like adding a method are actually breaking for us. We get around this by pinning the version.
